# Generated by Django 3.2.5 on 2021-10-23 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JEE_Paper_Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Paper_Title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(blank=True, choices=[('JEE Mains', 'JEE Mains'), ('NEET', 'NEET'), ('PAT', 'PAT'), ('GATE', 'GATE')], default='Jee', max_length=100)),
                ('marking_scheme', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', help_text='assigned marks for every questions', max_length=200)),
                ('minus_marking_scheme', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=200)),
                ('scheduled_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('remove_live_minutes', models.IntegerField(blank=True, default=15)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JEE_Physics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_No', models.IntegerField(default=0, help_text='increament every time for unique paper type')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('single', 'single'), ('write', 'write'), ('multiselect', 'multiselect')], default='single', help_text='Please enter your answerin option1 for write type questions', max_length=20)),
                ('option1', models.CharField(blank=True, max_length=500)),
                ('option2', models.CharField(blank=True, max_length=500)),
                ('option3', models.CharField(blank=True, max_length=500)),
                ('option4', models.CharField(blank=True, max_length=500)),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marking', models.FloatField(blank=True, default=0, help_text='assigned marks for this questions if same as title leave it.')),
                ('minus_marking', models.FloatField(blank=True, default=0, help_text='assigned negative marks for every questions if same as title leave it.')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=100)),
                ('explanation', models.TextField(blank=True, default='None')),
                ('paper_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JEE.jee_paper_title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JEE_Math',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_No', models.IntegerField(default=0, help_text='increament every time for unique paper type')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('single', 'single'), ('write', 'write'), ('multiselect', 'multiselect')], default='single', help_text='Please enter your answerin option1 for write type questions', max_length=20)),
                ('option1', models.CharField(blank=True, max_length=500)),
                ('option2', models.CharField(blank=True, max_length=500)),
                ('option3', models.CharField(blank=True, max_length=500)),
                ('option4', models.CharField(blank=True, max_length=500)),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marking', models.FloatField(blank=True, default=0, help_text='assigned marks for this questions if same as title leave it.')),
                ('minus_marking', models.FloatField(blank=True, default=0, help_text='assigned negative marks for every questions if same as title leave it.')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=100)),
                ('explanation', models.TextField(blank=True, default='None')),
                ('paper_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JEE.jee_paper_title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JEE_Chemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_No', models.IntegerField(default=0, help_text='increament every time for unique paper type')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('single', 'single'), ('write', 'write'), ('multiselect', 'multiselect')], default='single', help_text='Please enter your answerin option1 for write type questions', max_length=20)),
                ('option1', models.CharField(blank=True, max_length=500)),
                ('option2', models.CharField(blank=True, max_length=500)),
                ('option3', models.CharField(blank=True, max_length=500)),
                ('option4', models.CharField(blank=True, max_length=500)),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marking', models.FloatField(blank=True, default=0, help_text='assigned marks for this questions if same as title leave it.')),
                ('minus_marking', models.FloatField(blank=True, default=0, help_text='assigned negative marks for every questions if same as title leave it.')),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=100)),
                ('explanation', models.TextField(blank=True, default='None')),
                ('paper_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JEE.jee_paper_title')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
