# Generated by Django 3.2.5 on 2021-10-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JEE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jee_math',
            name='paper_title',
        ),
        migrations.RemoveField(
            model_name='jee_physics',
            name='paper_title',
        ),
        migrations.DeleteModel(
            name='JEE_Chemistry',
        ),
        migrations.DeleteModel(
            name='JEE_Math',
        ),
        migrations.DeleteModel(
            name='JEE_Paper_Title',
        ),
        migrations.DeleteModel(
            name='JEE_Physics',
        ),
    ]
