# Generated by Django 3.2.5 on 2021-10-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JEE', '0003_jeechemistry_jeemath_jeepapertitle_jeephysics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JeePhysics',
            new_name='Chemistry',
        ),
        migrations.RenameModel(
            old_name='JeeMath',
            new_name='Math',
        ),
        migrations.RenameModel(
            old_name='JeeChemistry',
            new_name='Physics',
        ),
    ]
