# Generated by Django 3.2.5 on 2021-10-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JEE', '0004_auto_20211023_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='math',
            name='paper_title',
        ),
        migrations.RemoveField(
            model_name='physics',
            name='paper_title',
        ),
        migrations.DeleteModel(
            name='Chemistry',
        ),
        migrations.DeleteModel(
            name='JeePaperTitle',
        ),
        migrations.DeleteModel(
            name='Math',
        ),
        migrations.DeleteModel(
            name='Physics',
        ),
    ]
