# Generated by Django 3.2 on 2021-11-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JEE', '0007_alter_topic_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
    ]
