# Generated by Django 3.2 on 2021-11-08 05:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JEE', '0008_remove_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=ckeditor.fields.RichTextField(default='new'),
            preserve_default=False,
        ),
    ]
