# Generated by Django 3.2 on 2021-11-08 06:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JEE', '0009_topic_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='Image',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='sldkjf'),
            preserve_default=False,
        ),
    ]
