# Generated by Django 3.2 on 2021-11-08 10:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('JEE', '0010_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='Ano',
            field=tinymce.models.HTMLField(default='dslkfj'),
            preserve_default=False,
        ),
    ]
