# Generated by Django 3.2 on 2021-11-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JEE', '0011_topic_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
    ]
