# Generated by Django 3.2 on 2021-10-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
