# Generated by Django 3.2.5 on 2021-10-10 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Queistion_Paper_Title', models.CharField(max_length=200)),
                ('exam_type', models.CharField(blank=True, choices=[('Jee', 'Jee'), ('Neet', 'Neet')], default='Jee', max_length=100)),
                ('hidden', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(blank=True, default=0, max_length=200)),
                ('attempts', models.IntegerField(blank=True, default=0)),
                ('answers', models.TextField(blank=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Physics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_No', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('single', 'single'), ('write', 'write'), ('multiselect', 'multiselect')], default='single', max_length=20)),
                ('option1', models.CharField(blank=True, max_length=500)),
                ('option2', models.CharField(blank=True, max_length=500)),
                ('option3', models.CharField(blank=True, max_length=500)),
                ('option4', models.CharField(blank=True, max_length=500)),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=100)),
                ('explanation', models.TextField(blank=True, default='None')),
                ('paper_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_No', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('single', 'single'), ('write', 'write'), ('multiselect', 'multiselect')], default='single', max_length=20)),
                ('option1', models.CharField(blank=True, max_length=500)),
                ('option2', models.CharField(blank=True, max_length=500)),
                ('option3', models.CharField(blank=True, max_length=500)),
                ('option4', models.CharField(blank=True, max_length=500)),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=100)),
                ('explanation', models.TextField(blank=True, default='None')),
                ('paper_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.title')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chemistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q_No', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('single', 'single'), ('write', 'write'), ('multiselect', 'multiselect')], default='single', max_length=20)),
                ('option1', models.CharField(blank=True, max_length=500)),
                ('option2', models.CharField(blank=True, max_length=500)),
                ('option3', models.CharField(blank=True, max_length=500)),
                ('option4', models.CharField(blank=True, max_length=500)),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=100)),
                ('explanation', models.TextField(blank=True, default='None')),
                ('paper_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.title')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
