# Generated by Django 3.2.5 on 2021-10-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physics',
            name='user',
            field=models.CharField(default='n', max_length=200),
        ),
    ]
