# Generated by Django 3.2.5 on 2021-10-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_physics_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physics',
            name='user',
        ),
    ]
