# Generated by Django 3.2.5 on 2021-10-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_title_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='end_hours',
        ),
    ]
