# Generated by Django 3.2.5 on 2021-10-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_physics_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='math',
            name='created_by',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
