# Generated by Django 3.2.5 on 2021-10-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_remove_title_end_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='remove_live',
            field=models.IntegerField(blank=True, default=15),
        ),
        migrations.AlterField(
            model_name='title',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('JEE Mains', 'JEE Mains'), ('NEET', 'NEET'), ('PAT', 'PAT'), ('GATE', 'GATE')], default='Jee', max_length=100),
        ),
    ]
