# Generated by Django 3.2.5 on 2021-10-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_math_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='math',
            name='created_by',
        ),
    ]
