# Generated by Django 3.2.5 on 2021-10-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20211022_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='Queistion_Paper_Title',
            new_name='Question_Paper_Title',
        ),
    ]
