# Generated by Django 3.2.5 on 2021-10-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_math_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='type',
            field=models.CharField(choices=[('single', 'single'), ('write', 'write'), ('multiselect', 'multiselect')], default='single', help_text='Please enter your answerin option1 for write type questions', max_length=20),
        ),
        migrations.AlterField(
            model_name='math',
            name='type',
            field=models.CharField(choices=[('single', 'single'), ('write', 'write'), ('multiselect', 'multiselect')], default='single', help_text='Please enter your answerin option1 for write type questions', max_length=20),
        ),
        migrations.AlterField(
            model_name='physics',
            name='type',
            field=models.CharField(choices=[('single', 'single'), ('write', 'write'), ('multiselect', 'multiselect')], default='single', help_text='Please enter your answerin option1 for write type questions', max_length=20),
        ),
    ]
