# Generated by Django 3.2.5 on 2021-10-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20211010_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='Q_No',
            field=models.IntegerField(default=0, help_text='increament every time for unique paper type'),
        ),
        migrations.AlterField(
            model_name='math',
            name='Q_No',
            field=models.IntegerField(default=0, help_text='increament every time for unique paper type'),
        ),
        migrations.AlterField(
            model_name='physics',
            name='Q_No',
            field=models.IntegerField(default=0, help_text='increament every time for unique paper type'),
        ),
    ]
