# Generated by Django 3.2.5 on 2021-10-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_rename_remove_live_title_remove_live_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculture',
            name='marking',
            field=models.FloatField(blank=True, default=0, help_text='assigned marks for every questions'),
        ),
        migrations.AddField(
            model_name='agriculture',
            name='minus_marking',
            field=models.FloatField(blank=True, default=0, help_text='assigned negative marks for every questions if same as title leave it.'),
        ),
        migrations.AddField(
            model_name='biology',
            name='marking',
            field=models.FloatField(blank=True, default=0, help_text='assigned marks for every questions'),
        ),
        migrations.AddField(
            model_name='biology',
            name='minus_marking',
            field=models.FloatField(blank=True, default=0, help_text='assigned negative marks for every questions if same as title leave it.'),
        ),
        migrations.AddField(
            model_name='chemistry',
            name='marking',
            field=models.FloatField(blank=True, default=0, help_text='assigned marks for every questions'),
        ),
        migrations.AddField(
            model_name='chemistry',
            name='minus_marking',
            field=models.FloatField(blank=True, default=0, help_text='assigned negative marks for every questions if same as title leave it.'),
        ),
        migrations.AddField(
            model_name='math',
            name='marking',
            field=models.FloatField(blank=True, default=0, help_text='assigned marks for every questions'),
        ),
        migrations.AddField(
            model_name='math',
            name='minus_marking',
            field=models.FloatField(blank=True, default=0, help_text='assigned negative marks for every questions if same as title leave it.'),
        ),
        migrations.AddField(
            model_name='physics',
            name='marking',
            field=models.FloatField(blank=True, default=0, help_text='assigned marks for every questions'),
        ),
        migrations.AddField(
            model_name='physics',
            name='minus_marking',
            field=models.FloatField(blank=True, default=0, help_text='assigned negative marks for every questions if same as title leave it.'),
        ),
    ]
