# Generated by Django 3.2 on 2021-10-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_auto_20211023_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='subjects',
            field=models.CharField(blank=True, choices=[('Math', 'Math'), ('Chemsitry', 'Chemsitry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Agriculture', 'Agriculture')], default='Math', max_length=200),
        ),
    ]
