# Generated by Django 3.2.5 on 2021-10-10 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_alter_studentdata_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='chemistry_answers',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='math_answers',
        ),
        migrations.RemoveField(
            model_name='studentdata',
            name='physics_answers',
        ),
    ]
