# Generated by Django 3.2 on 2021-10-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_title_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='subjects',
            field=models.CharField(blank=True, default='Math', max_length=200),
        ),
    ]
