# Generated by Django 3.2 on 2021-11-19 11:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_auto_20211109_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='Front_image',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
