# Generated by Django 3.2 on 2021-11-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_title_front_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='Front_image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
