# Generated by Django 3.2.9 on 2021-11-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_alter_title_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='feedback',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
