# Generated by Django 3.2.9 on 2021-11-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_auto_20211129_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coa',
            name='paper_title',
        ),
        migrations.RemoveField(
            model_name='computernetworks',
            name='paper_title',
        ),
        migrations.RemoveField(
            model_name='cybersecurity',
            name='paper_title',
        ),
        migrations.RemoveField(
            model_name='datascience',
            name='paper_title',
        ),
        migrations.RemoveField(
            model_name='dbms',
            name='paper_title',
        ),
        migrations.RemoveField(
            model_name='digitalelectronics',
            name='paper_title',
        ),
        migrations.RemoveField(
            model_name='dsa',
            name='paper_title',
        ),
        migrations.RemoveField(
            model_name='operatingsystem',
            name='paper_title',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='COA',
        ),
        migrations.DeleteModel(
            name='ComputerNetworks',
        ),
        migrations.DeleteModel(
            name='CyberSecurity',
        ),
        migrations.DeleteModel(
            name='DataScience',
        ),
        migrations.DeleteModel(
            name='DBMS',
        ),
        migrations.DeleteModel(
            name='DigitalElectronics',
        ),
        migrations.DeleteModel(
            name='DSA',
        ),
        migrations.DeleteModel(
            name='OperatingSystem',
        ),
    ]
